name: Trigger CircleCI
on:
  pull_request:
jobs:
  trigger-circleci:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger Build
        id: trigger-circle-ci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
